version: "3.3"

networks:
  traefik:
    name: traefik

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    command:
      - '--log.level=debug'
      - '--api.insecure=false'
      - '--pilot.dashboard=false'
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http3=true"
      - "--experimental.http3=true"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--certificatesresolvers.default.acme.email=TODOCHANGEME@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=4000
      - USER_GID=4000
    restart: unless-stopped
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.localhost`)"
      - "traefik.http.routers.gitea.entrypoints=web-secure"
      - "traefik.http.routers.gitea.tls.certresolver=default"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.gitea_compress.compress=true"
      - "traefik.http.routers.gitea.middlewares=gitea_compress"
    networks:
      - traefik     
  drone:
    image: drone/drone:2
    container_name: drone
    restart: unless-stopped
    volumes:
      - ./data/drone:/data
    environment:
      - DRONE_GITEA_SERVER=http://git.localhost
      - DRONE_GITEA_CLIENT_ID=TODO
      - DRONE_GITEA_CLIENT_SECRET=TODO
      - DRONE_RPC_SECRET=TODO
      - DRONE_SERVER_HOST=ci.localhost
      - DRONE_SERVER_PROTO=https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`ci.localhost`)"
      - "traefik.http.routers.drone.entrypoints=web-secure"
      - "traefik.http.routers.drone.tls.certresolver=default"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
      - "traefik.http.middlewares.drone_compress.compress=true"
      - "traefik.http.routers.drone.middlewares=drone_compress"
    networks:
      - traefik

  # TODO: remove
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=mattermost
      - POSTGRES_DB=mattermost
    networks:
      - traefik

  mattermost:
    # TODO: remove
    depends_on:
      - db
    image: mattermost/mattermost-team-edition
    container_name: mattermost
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ./data/mattermost/config:/mattermost/config:rw
      - ./data/mattermost/data:/mattermost/data:rw
      - ./data/mattermost/logs:/mattermost/logs:rw
      - ./data/mattermost/plugins:/mattermost/plugins:rw
      - ./data/mattermost/client-plugins:/mattermost/client/plugins:rw
      - ./data/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - TZ=Europe/Rome
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=https://chat.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`chat.localhost`)"
      - "traefik.http.routers.mattermost.entrypoints=web-secure"
      - "traefik.http.routers.mattermost.tls.certresolver=default"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
      - "traefik.http.middlewares.mattermost_compress.compress=true"
      - "traefik.http.routers.mattermost.middlewares=mattermost_compress"
    networks:
      - traefik
