---
- name: SWE
  hosts: all
  tasks:
  - name: Setup security
    ansible.builtin.import_tasks: tasks/security.yaml
  - name: Setup postgresql
    ansible.builtin.import_tasks: tasks/postgresql.yaml
  - name: Setup Gitlab
    ansible.builtin.import_tasks: tasks/gitlab.yaml
  - name: Setup Jenkins
    ansible.builtin.import_tasks: tasks/jenkins.yaml
  - name: Setup Mattermost
    ansible.builtin.import_tasks: tasks/mattermost.yaml
  - name: Setup Sonarqube
    ansible.builtin.import_tasks: tasks/sonarqube.yaml
  - name: Setup Taiga
    ansible.builtin.import_tasks: tasks/taiga.yaml
  - name: Setup homepage
    ansible.builtin.import_tasks: tasks/homepage.yaml
  - name: Setup Docker
    ansible.builtin.import_tasks: tasks/docker.yaml
  - name: Setup backup
    ansible.builtin.import_tasks: tasks/backup.yaml
