concurrent = {{ ansible_processor_vcpus * 2}}
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner0"
  url = "https://git.{{ domain }}/"
  executor = "docker"
  builds_dir = "/ramfs"
  cache_dir = "/ramfs/cache"
  token = "{{ gitlab_runner_token }}"
  [runners.custom_build_dir]
    enabled = true
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 300000
    pull_policy = "if-not-present"
    volumes = [
      "/ramfs:/ramfs:rw",
      "/cache:/ramfs/cache:rw",
      "/var/run/docker.sock:/var/run/docker.sock"
    ]
