- name: Copy backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /swe/backup.sh
    owner: root
    group: root
    mode: '0700'
- name: Backup cronjob
  ansible.builtin.cron:
    name: "Daily backup"
    hour: "4"
    minute: "0"
    user: "root"
    job: "/swe/backup.sh"
- name: Copy restore script
  ansible.builtin.template:
    src: restore.sh.j2
    dest: /swe/restore.sh
    owner: root
    group: root
    mode: '0700'
