- name: Set rmem_max for HTTP3
  ansible.builtin.shell: |
    sysctl -w net.core.rmem_max=2500000

- name: Add Docker repo
  block:
    - name: Download the Docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc

    - name: Add the Docker repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
        state: present

- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - python3-docker
    state: latest
    update_cache: yes

- name: Read Mattermost postgres password
  ansible.builtin.slurp:
    src: /root/mattermost_password.txt
  register: mattermost_password

- name: Read Sonarqube postgres password
  ansible.builtin.slurp:
    src: /root/sonarqube_password.txt
  register: sonarqube_password

- name: Print mattermost password
  ansible.builtin.debug:
    var: mattermost_password

- name: Read Taiga postgres password
  ansible.builtin.slurp:
    src: /root/taiga_password.txt
  register: taiga_password

- name: Read Taiga secret
  ansible.builtin.slurp:
    src: /root/taiga_secret.txt
  register: taiga_secret

- name: Copy Docker compose
  ansible.builtin.template:
    src: ../docker-compose.yml.j2
    dest: /root/docker-compose.yml
    owner: root
    mode: '0700'

- name: Restart and enable Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes

- name: Run `docker-compose up`
  community.docker.docker_compose:
    project_src: /root/
    build: false
    remove_orphans: true
  register: docker_compose_output

- name: Print docker compose output
  ansible.builtin.debug:
    var: docker_compose_output
