- name: Create a file for Gitea DB password
  ansible.builtin.file:
    path: /root/gitea_password.txt
    state: touch
    mode: '0700'
    owner: root
- name: Install Git
  ansible.builtin.package:
    name: 
    - git
    - git-lfs
    state: latest
    update_cache: yes
- name: Add the group 'git'
  ansible.builtin.group:
    name: git
    system: yes
    gid: 4000
- name: Add the user 'git'
  ansible.builtin.user:
    system: yes
    shell: /usr/bin/nologin
    group: git
    name: git
    uid: 4000
- name: Generate random password for gitea postgresql database
  ansible.builtin.set_fact:
    gitea_db_password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
- name: Create the gitea postgresql user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: gitea
    password: '{{ gitea_db_password }}'
-  name: Write Gitea DB password to a file
   ansible.builtin.copy:
    content: "{{ gitea_db_password }}"
    dest: "/root/gitea_password.txt"
- name: Create the gitea postgresql database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: giteadb
    encoding: UTF-8
    lc_collate: en_GB.UTF-8 # TODO check with locale -a
    lc_ctype: en_GB.UTF-8
    template: template0
    owner: gitea
- name: Enable postgresql password authentication
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: local
    databases: giteadb
    users: gitea
    method: scram-sha-256
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
