- name: Create the '/ramfs' directory
  ansible.builtin.file:
    path: /ramfs
    state: directory
    owner: root
    group: root
    mode: '0770'

- name: Mount a 16G tmpfs to '/ramfs'
  mount:
    name: '/ramfs'
    src: tmpfs
    fstype: tmpfs
    opts: "nodev,nosuid,size={{ gitlab_runner_ramfs_size }}"
    state: mounted

- name: Create the '/gitlab/config' directory
  ansible.builtin.file:
    path: /gitlab/config
    state: directory
    owner: 998
    group: 998
    mode: '0770'

- name: Create the '/gitlab/log' directory
  ansible.builtin.file:
    path: /gitlab/log
    state: directory
    owner: 998
    group: 998
    mode: '0770'

- name: Create the '/gitlab/data' directory
  ansible.builtin.file:
    path: /gitlab/data
    state: directory
    owner: 999
    group: 999
    mode: '0770'

- name: Create the 'runner_config.toml' for the GitLab runner
  ansible.builtin.template:
    src: ../runner_config.toml
    dest: /swe/runner_config.toml
    owner: root
    group: root
    mode: '0770'
