- name: Create the '/gitlab/config' directory
  ansible.builtin.file:
    path: /gitlab/config
    state: directory
    owner: 998
    group: 998
    mode: '0770'
- name: Create the '/gitlab/log' directory
  ansible.builtin.file:
    path: /gitlab/log
    state: directory
    owner: 998
    group: 998
    mode: '0770'
- name: Create the '/gitlab/data' directory
  ansible.builtin.file:
    path: /gitlab/data
    state: directory
    owner: 999
    group: 999
    mode: '0770'
