- name: Create a file for Mattermost DB password
  ansible.builtin.file:
    path: /root/mattermost_password.txt
    state: touch
    mode: '0700'
    owner: root
- name: Create the '/mattermost' directories
  ansible.builtin.file:
    path: '{{item}}'
    state: directory
    owner: 2000
    group: 2000
    mode: '0770'
  loop:
   - '/mattermost/config'
   - '/mattermost/data'
   - '/mattermost/logs'
   - '/mattermost/plugins'
   - '/mattermost/client-plugins'
   - '/mattermost/belve-indexes'
- name: Check if mattermost_password.txt exists
  ansible.builtin.stat:
    path: /root/mattermost_password.txt
  register: mattermost_password_file
- name: Generate password for Mattermost postgresql database
  block:
  - name: Generate random password for Mattermost postgresql database
    ansible.builtin.set_fact:
      mattermost_db_password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
  - name: Write Mattermost DB password to a file
    ansible.builtin.copy:
      content: "{{ mattermost_db_password }}"
      dest: "/root/mattermost_password.txt"
  when: not mattermost_password_file.stat.exists
- name: Generate password for Sonarqube postgresql database
  ansible.builtin.slurp:
    src: /root/mattermost_password.txt
  register: mattermost_db_password
  when: mattermost_password_file.stat.exists
- name: Create the Mattermost postgresql database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: mattermost
    encoding: UTF-8
    lc_collate: en_US.UTF-8 # TODO check with locale -a
    lc_ctype: en_US.UTF-8
    template: template0
- name: Create the mattermost postgresql user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: mmuser
    password: '{{ mattermost_db_password }}'
- name: GRANT ALL PRIVILEGES ON DATABASE mattermost TO mmuser
  become: yes
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    obj: mattermost
    role: mmuser
- name: Modify the file pg_hba.conf to allow the Mattermost server to communicate with the database
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    users: all
    databases: all
    method: trust
- name: Restart PostgresSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
