- name: Set Postgresql version
  ansible.builtin.set_fact:
    postgresql_version: 13

- name: Install sudo
  ansible.builtin.package:
    name:
      - sudo

- name: Add PostgreSQL repo
  block:
    - name: Download the PostgreSQL key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/trusted.gpg.d/postgresql.asc

    - name: Add the PostgreSQL repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
        state: present

- name: Install PostgreSQL
  ansible.builtin.package:
    name:
      - 'postgresql-{{ postgresql_version }}'
      - libpq5
      - python3-psycopg2
    state: latest
    update_cache: yes

- name: Restart and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Make postgres listen on 0.0.0.0
  ansible.builtin.lineinfile:
    path: '/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf'
    line: "listen_addresses = '*'"
- name: Modify the file pg_hba.conf to allow the Mattermost server to communicate with the database
  community.postgresql.postgresql_pg_hba:
    dest: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'
    contype: host
    users: all
    databases: all
    method: scram-sha-256
    source: 0.0.0.0/0

- name: Restart and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
