- name: Install ufw and fail2ban
  ansible.builtin.package:
    name: 
    - ufw
    - fail2ban
    state: latest
- name: Allow TCP on some ports
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 2222
    - 22
    - 80
    - 443
- name: Allow UDP for 443
  community.general.ufw:
    rule: allow
    port: 443
- name: Copy default fail2ban config
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
- name: Enable and start service fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
- name: Enable and start service ufw
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes
