- name: Set max_map_count
  ansible.builtin.shell: |
    sysctl -w vm.max_map_count=262144
- name: Check if sonarqube_password.txt exists
  ansible.builtin.stat:
    path: /root/sonarqube_password.txt
  register: sonarqube_password_file
- name: Generate password for Sonarqube postgresql database
  block:
  - name: Generate random password for Sonarqube postgresql database
    ansible.builtin.set_fact:
      sonarqube_db_password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
  - name: Write Sonarqube DB password to a file
    ansible.builtin.copy:
      content: "{{ sonarqube_db_password }}"
      dest: "/root/sonarqube_password.txt"
  when: not sonarqube_password_file.stat.exists
- name: Generate password for Sonarqube postgresql database
  ansible.builtin.slurp:
    src: /root/sonarqube_password.txt
  register: sonarqube_db_password
  when: sonarqube_password_file.stat.exists
- name: Create the Sonarqube postgresql database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: sonarqube
    encoding: UTF-8
    lc_collate: en_US.UTF-8 # TODO check with locale -a
    lc_ctype: en_US.UTF-8
    template: template0
- name: Create the sonarqube postgresql user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: squser
    password: '{{ sonarqube_db_password }}'
- name: GRANT ALL PRIVILEGES ON DATABASE sonarqube TO squser
  become: yes
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    obj: sonarqube
    role: squser
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
