- name: Create a file for Woodpecker DB password
  ansible.builtin.file:
    path: /root/woodpecker_password.txt
    state: touch
    mode: '0700'
    owner: root
- name: Create the '/woodpecker' directory
  ansible.builtin.file:
    path: /woodpecker
    state: directory
    mode: '0700'
    owner: root
- name: Generate random password for Woodpecker postgresql database
  ansible.builtin.set_fact:
    woodpecker_db_password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
-  name: Write Woodpecker DB password to a file
   ansible.builtin.copy:
    content: "{{ woodpecker_db_password }}"
    dest: "/root/woodpecker_password.txt"
- name: Create the Woodpecker postgresql database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: woodpecker
    encoding: UTF-8
    lc_collate: en_US.UTF-8 # TODO check with locale -a
    lc_ctype: en_US.UTF-8
    template: template0
- name: Create the woodpecker postgresql user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: mmuser
    password: '{{ woodpecker_db_password }}'
- name: GRANT ALL PRIVILEGES ON DATABASE woodpecker TO mmuser
  community.postgresql.postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    obj: woodpecker
    role: mmuser
